apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: product-catalog-dev
  namespace: argocd
  labels:
    env: dev
spec:
  project: default
  source:
    repoURL: https://github.com/Chaima-Jlassi/SmartDeploy.git
    targetRevision: dev
    path: helm
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true