apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: product-catalog-prod
  namespace: argocd
  labels:
    env: prod
spec:
  project: default
  source:
    repoURL: https://github.com/Chaima-Jlassi/SmartDeploy.git
    targetRevision: main
    path: helm
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true