namespace: staging
serviceName: product-catalog
nodeEnv: staging

replicaCount: 1

image:
  repository: smartdeployacr.azurecr.io/product-catalog
  tag: latest

service:
  port: 3000

resources:
  requests:
    cpu: 150m
    memory: 192Mi
  limits:
    cpu: 300m
    memory: 384Mi

hpa:
  minReplicas: 1
  maxReplicas: 3
  cpuThreshold: 65