name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test product-catalog
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: product-catalog

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: product-catalog/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  security-and-push:
    name: Scan and push to ACR
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: az acr login --name ${{ secrets.ACR_NAME }}

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ secrets.ACR_NAME }}.azurecr.io/product-catalog:${{ github.sha }} \
            ./product-catalog

            - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.ACR_NAME }}.azurecr.io/product-catalog:${{ github.sha }}
          format: table
          exit-code: 1
          severity: CRITICAL
          trivyignores: product-catalog/.trivyignore

      - name: Push image to ACR
        run: |
          docker push \
            ${{ secrets.ACR_NAME }}.azurecr.io/product-catalog:${{ github.sha }}